# https://taskfile.dev

version: "3"

tasks:
  docker-build-push:
    cmds:
      - docker buildx build --push --file ./Dockerfile --tag gsource.krabcybernode.ru/nd/miniapp-vk:latest .
    silent: true
